micronaut.control-panel.panels.tracing.enabled = true
micronaut.control-panel.panels.tracing.title = Tracing Diagnostics
micronaut.control-panel.panels.tracing.icon = fa-route
micronaut.control-panel.panels.tracing.order = 30
