micronaut.control-panel.panels.liquibase.enabled = true
micronaut.control-panel.panels.liquibase.title = Liquibase
micronaut.control-panel.panels.liquibase.icon = fa-database
micronaut.control-panel.panels.liquibase.order = 30
