micronaut.control-panel.panels.oci-sdk-clients.enabled = true
micronaut.control-panel.panels.oci-sdk-clients.title = OCI SDK Clients
micronaut.control-panel.panels.oci-sdk-clients.icon = si si-oracle
micronaut.control-panel.panels.oci-sdk-clients.order = 30
