micronaut.control-panel.panels.jmx.enabled = true
micronaut.control-panel.panels.jmx.title = JMX
micronaut.control-panel.panels.jmx.icon = fa-network-wired
micronaut.control-panel.panels.jmx.order = 30
