micronaut.control-panel.panels.views.enabled = true
micronaut.control-panel.panels.views.title = Views
micronaut.control-panel.panels.views.icon = fa-window-maximize
micronaut.control-panel.panels.views.order = 25
