micronaut.control-panel.panels.servlet-runtime.title = Servlet Runtime
micronaut.control-panel.panels.servlet-runtime.icon = fa-server
micronaut.control-panel.panels.servlet-runtime.order = 25
micronaut.control-panel.panels.servlet-runtime.enabled = true
