micronaut.control-panel.panels.http-client.enabled = true
micronaut.control-panel.panels.http-client.icon = fas fa-network-wired
micronaut.control-panel.panels.http-client.order = 80
micronaut.control-panel.panels.http-client.title = HTTP Clients
