plugins {
    id 'groovy'
    id 'io.micronaut.application'
}

application {
    mainClass = 'example.Application'
}

micronaut {
    version libs.versions.micronaut.platform.get()
    coreVersion.set(libs.versions.micronaut.asProvider().get())
    runtime("netty")
    testRuntime("junit5")
}

dependencies {
    annotationProcessor mnSerde.micronaut.serde.processor
    implementation mnSerde.micronaut.serde.jackson

    runtimeOnly projects.micronautControlPanelUi
    implementation projects.micronautControlPanelManagement

    implementation mn.micronaut.management
    runtimeOnly mnLogging.logback.classic
    runtimeOnly mn.snakeyaml

    testImplementation mn.micronaut.http.client
    testImplementation mnTest.micronaut.test.junit5
    testImplementation libs.playwright
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.register('playwrightCodegen', JavaExec) {
    mainClass = 'com.microsoft.playwright.CLI'
    classpath = sourceSets.test.runtimeClasspath
    args 'codegen', 'http://localhost:8080/control-panel'
}

tasks.register('playwrightInstall', JavaExec) {
    mainClass = 'com.microsoft.playwright.CLI'
    classpath = sourceSets.test.runtimeClasspath
    args 'install', '--with-deps'
}

tasks.named('test') {
    dependsOn tasks.named('playwrightInstall')
}

graalvmNative {
    agent {
        enabled.set(true)
        defaultMode.set("conditional")
        modes {
            conditional {
                userCodeFilterPath.set("src/main/native-image/filters/user-code-filter.json")
                callerFilterFiles.from("src/main/native-image/filters/user-code-filter.json")
                accessFilterFiles.from("src/main/native-image/filters/user-code-filter.json")
                builtinCallerFilter.set(true)
                builtinHeuristicFilter.set(true)
                enableExperimentalPredefinedClasses.set(true)
                enableExperimentalUnsafeAllocationTracing.set(true)
                trackReflectionMetadata.set(true)
            }
        }
    }
    metadataCopy {
        inputTaskNames.add("run")
        outputDirectories.add("${rootDir.toString()}/control-panel-ui/src/main/resources/META-INF/native-image/io.micronaut.controlpanel/micronaut-control-panel-ui")
        mergeWithExisting.set(false)
    }
    binaries.all {
        resources.autodetect()
        quickBuild.set(true)
    }
}
