/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.controlpanel.panels.graalpy;

import io.micronaut.context.BeanContext;
import io.micronaut.context.DefaultBeanContext;
import io.micronaut.context.Qualifier;
import io.micronaut.core.annotation.AnnotationMetadata;
import io.micronaut.core.annotation.ReflectiveAccess;
import io.micronaut.core.reflect.ClassUtils;
import io.micronaut.core.type.Argument;
import io.micronaut.inject.BeanDefinition;
import io.micronaut.inject.ExecutableMethod;
import jakarta.inject.Singleton;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Discovers the Python-backed bean definitions generated by {@code micronaut-inject-python}.
 *
 * <p>The Micronaut Core Python annotations are {@code @Internal}, so they are never referenced at compile time.
 * They are matched by fully qualified name through {@link AnnotationMetadata}, which degrades to an explicit
 * empty state if Core ever renames them.</p>
 */
@Singleton
public final class PythonBeanScanner {

    /**
     * Annotation added by {@code micronaut-inject-python} to generated Python module bridge stubs.
     */
    static final String PYTHON_MODULE_ANNOTATION = "io.micronaut.context.python.annotation.PythonModule";
    /**
     * Annotation added by {@code micronaut-inject-python} to generated Python class bridge stubs.
     */
    static final String PYTHON_CLASS_ANNOTATION = "io.micronaut.context.python.annotation.PythonClass";
    /**
     * Scope applied to Python beans that are bound to a pooled GraalPy context.
     */
    static final String CONTEXT_POOLED_SCOPE = "io.micronaut.context.python.scope.ContextPooled";
    /**
     * Scope {@code @ContextPooled} is built from. Because {@code @ContextPooled} is declared with
     * {@code RetentionPolicy.CLASS}, Micronaut collapses it into this meta-annotation in the bean definition
     * metadata, so a prototype-scoped Python bean is a context-pooled one.
     */
    static final String PROTOTYPE_SCOPE = "io.micronaut.context.annotation.Prototype";

    private static final String KIND_MODULE = "module";
    private static final String KIND_CLASS = "class";

    private final BeanContext beanContext;

    PythonBeanScanner(BeanContext beanContext) {
        this.beanContext = beanContext;
    }

    /**
     * @return whether the Core Python bean annotations are resolvable on the current classpath
     */
    boolean metadataAvailable() {
        ClassLoader classLoader = beanContext.getClassLoader();
        return ClassUtils.isPresent(PYTHON_MODULE_ANNOTATION, classLoader)
            || ClassUtils.isPresent(PYTHON_CLASS_ANNOTATION, classLoader);
    }

    /**
     * @return the Python-backed bean definitions, sorted by Java type then bean name
     */
    List<PythonBean> scan() {
        return beanContext.getAllBeanDefinitions()
            .stream()
            .filter(PythonBeanScanner::isPythonBean)
            .map(this::pythonBean)
            .sorted(Comparator.comparing(PythonBean::javaType).thenComparing(PythonBean::beanName))
            .toList();
    }

    /**
     * @return the number of Python-backed bean definitions, without building method signatures
     */
    long count() {
        return beanContext.getAllBeanDefinitions()
            .stream()
            .filter(PythonBeanScanner::isPythonBean)
            .count();
    }

    private static boolean isPythonBean(BeanDefinition<?> definition) {
        AnnotationMetadata metadata = definition.getAnnotationMetadata();
        return metadata.hasAnnotation(PYTHON_MODULE_ANNOTATION)
            || metadata.hasDeclaredAnnotation(PYTHON_MODULE_ANNOTATION)
            || metadata.hasAnnotation(PYTHON_CLASS_ANNOTATION)
            || metadata.hasDeclaredAnnotation(PYTHON_CLASS_ANNOTATION);
    }

    private PythonBean pythonBean(BeanDefinition<?> definition) {
        AnnotationMetadata metadata = definition.getAnnotationMetadata();
        boolean module = metadata.hasAnnotation(PYTHON_MODULE_ANNOTATION) || metadata.hasDeclaredAnnotation(PYTHON_MODULE_ANNOTATION);
        String kind = module ? KIND_MODULE : KIND_CLASS;
        String annotation = module ? PYTHON_MODULE_ANNOTATION : PYTHON_CLASS_ANNOTATION;
        String identity = module
            ? metadata.stringValue(annotation, "moduleName").orElse("")
            : displayName(metadata);
        String packageName = metadata.stringValue(annotation, "packageName").orElse("");
        List<String> nestedMembers = module
            ? List.of()
            : Arrays.stream(metadata.stringValues(annotation, "nestedMemberNames")).filter(name -> !name.isBlank()).toList();
        String scopeName = definition.getScopeName().orElse("");
        boolean pooled = CONTEXT_POOLED_SCOPE.equals(scopeName)
            || PROTOTYPE_SCOPE.equals(scopeName)
            || metadata.hasAnnotation(CONTEXT_POOLED_SCOPE);
        return new PythonBean(
            definition.getName(),
            definition.getBeanType().getName(),
            kind,
            identity,
            packageName,
            nestedMembers,
            pooled ? "Prototype (@ContextPooled)" : simpleName(scopeName),
            qualifierName(definition),
            pooled ? "Per pooled context" : registrationState(definition),
            methodSignatures(definition)
        );
    }

    private static String displayName(AnnotationMetadata metadata) {
        return metadata.stringValue(PYTHON_CLASS_ANNOTATION, "displayName")
            .filter(value -> !value.isBlank())
            .or(() -> metadata.stringValue(PYTHON_CLASS_ANNOTATION, "rootName"))
            .orElse("");
    }

    private static String simpleName(String className) {
        if (className.isBlank()) {
            return "Unknown";
        }
        int lastDot = className.lastIndexOf('.');
        return lastDot < 0 ? className : className.substring(lastDot + 1);
    }

    private static String qualifierName(BeanDefinition<?> definition) {
        Qualifier<?> qualifier = definition.getDeclaredQualifier();
        return qualifier == null ? "Default" : qualifier.toString();
    }

    /**
     * Reports the instantiation state without ever forcing bean creation.
     *
     * @param definition the bean definition
     * @return a display state
     */
    private String registrationState(BeanDefinition<?> definition) {
        if (beanContext instanceof DefaultBeanContext defaultBeanContext) {
            return defaultBeanContext.getActiveBeanRegistrations(definition.getBeanType()).isEmpty()
                ? "Not created"
                : "Created";
        }
        return "Unknown";
    }

    private static List<MethodSignature> methodSignatures(BeanDefinition<?> definition) {
        Collection<ExecutableMethod<?, ?>> executableMethods = new ArrayList<>(definition.getExecutableMethods());
        if (!executableMethods.isEmpty()) {
            return executableMethods.stream()
                .filter(PythonBeanScanner::isUserMethod)
                .map(PythonBeanScanner::methodSignature)
                .sorted(Comparator.comparing(MethodSignature::name).thenComparing(MethodSignature::signature))
                .toList();
        }
        return Arrays.stream(definition.getBeanType().getMethods())
            .filter(PythonBeanScanner::isUserMethod)
            .map(PythonBeanScanner::methodSignature)
            .sorted(Comparator.comparing(MethodSignature::name).thenComparing(MethodSignature::signature))
            .toList();
    }

    private static boolean isUserMethod(ExecutableMethod<?, ?> method) {
        return isUserMethod(method.getTargetMethod());
    }

    private static boolean isUserMethod(Method method) {
        return method.getDeclaringClass() != Object.class
            && !method.isSynthetic()
            && !method.isBridge()
            && !Modifier.isStatic(method.getModifiers());
    }

    private static MethodSignature methodSignature(ExecutableMethod<?, ?> method) {
        String name = method.getMethodName();
        String returnType = displayType(method.getReturnType().asArgument());
        String parameters = Arrays.stream(method.getArguments())
            .map(PythonBeanScanner::displayParameter)
            .collect(Collectors.joining(", "));
        return new MethodSignature(name, returnType, parameters, returnType + " " + name + "(" + parameters + ")");
    }

    private static MethodSignature methodSignature(Method method) {
        String name = method.getName();
        String returnType = displayType(method.getGenericReturnType());
        String parameters = Arrays.stream(method.getGenericParameterTypes())
            .map(PythonBeanScanner::displayType)
            .collect(Collectors.joining(", "));
        return new MethodSignature(name, returnType, parameters, returnType + " " + name + "(" + parameters + ")");
    }

    private static String displayParameter(Argument<?> argument) {
        return displayType(argument) + " " + argument.getName();
    }

    private static String displayType(Argument<?> argument) {
        return argument.getTypeString(false).replace("java.lang.", "");
    }

    private static String displayType(Type type) {
        return type.getTypeName().replace("java.lang.", "");
    }

    /**
     * A Python-backed bean definition generated by {@code micronaut-inject-python}.
     *
     * @param beanName bean definition name
     * @param javaType generated Java bridge type
     * @param kind {@code module} or {@code class}
     * @param pythonIdentity Python module name or class display name
     * @param packageName Python package name
     * @param nestedMembers nested member names for Python classes
     * @param scope bean scope
     * @param qualifier bean qualifier
     * @param state instantiation state observed without creating the bean
     * @param methods bridge method signatures
     */
    @ReflectiveAccess
    public record PythonBean(
        String beanName,
        String javaType,
        String kind,
        String pythonIdentity,
        String packageName,
        List<String> nestedMembers,
        String scope,
        String qualifier,
        String state,
        List<MethodSignature> methods) {

        /**
         * @return whether bridge method signatures are available
         */
        public boolean hasMethods() {
            return !methods.isEmpty();
        }

        /**
         * @return bridge method count
         */
        public int methodCount() {
            return methods.size();
        }

        /**
         * @return whether nested member names are available
         */
        public boolean hasNestedMembers() {
            return !nestedMembers.isEmpty();
        }

        /**
         * @return whether a Python package name is available
         */
        public boolean hasPackageName() {
            return !packageName.isBlank();
        }
    }

    /**
     * Java bridge method signature.
     *
     * @param name method name
     * @param returnType return type
     * @param parameters parameter list
     * @param signature display signature
     */
    @ReflectiveAccess
    public record MethodSignature(String name, String returnType, String parameters, String signature) {
    }
}
