micronaut.control-panel.panels.flyway.enabled = true
micronaut.control-panel.panels.flyway.title = Flyway
micronaut.control-panel.panels.flyway.icon = fa-code-branch
micronaut.control-panel.panels.flyway.order = 30
