datasources:
  my-postgres:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
  hibernate-reporting:
    db-type: postgres
    driver-class-name: org.postgresql.Driver

jpa:
  default:
    enabled: true
    entity-scan:
      packages: example
    properties:
      hibernate.hbm2ddl.auto: create-drop
  my-postgres:
    enabled: true
    entity-scan:
      packages: example
    properties:
      hibernate.hbm2ddl.auto: create-drop
      hibernate.cache.region.factory_class: jcache
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.javax.cache.missing_cache_strategy: create
      hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
  hibernate-reporting:
    enabled: true
    entity-scan:
      packages: example
    properties:
      hibernate.hbm2ddl.auto: create-drop
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
  my-oracle:
    enabled: false
