test-resources:
  containers:
    hazelcast:
      image-name: hazelcast/hazelcast
      hostnames:
        - hazelcast.host
      exposed-ports:
        - hazelcast.port: 5701

hazelcast:
  enabled: true
  client:
    cluster-name: dev
    network:
      addresses:
        - ${hazelcast.host}:${hazelcast.port}
