micronaut.router.static-resources.css.mapping=/micronaut-control-panel/css/*.css
micronaut.router.static-resources.css.paths=classpath\:static/css
micronaut.router.static-resources.js.mapping=/micronaut-control-panel/js/*.js
micronaut.router.static-resources.js.paths=classpath\:static/js
micronaut.router.static-resources.img.mapping=/micronaut-control-panel/img/*.svg
micronaut.router.static-resources.img.paths=classpath\:static/img
