micronaut.control-panel.panels.toml.enabled = true
micronaut.control-panel.panels.toml.title = TOML Configuration
micronaut.control-panel.panels.toml.icon = fa-file-code
micronaut.control-panel.panels.toml.order = 15
