micronaut.control-panel.panels.crac.enabled = true
micronaut.control-panel.panels.crac.title = CRaC
micronaut.control-panel.panels.crac.icon = fa-arrows-rotate
micronaut.control-panel.panels.crac.order = 35
