#
# This file is used to declare the list of libraries
# which are used as dependencies in the project.
# See https://docs.gradle.org/7.4.2/userguide/platforms.html#sub:central-declaration-of-dependencies
#
# For Micronaut, we have 3 kinds of dependencies:
#   - managed dependencies, which are exposed to consumers via a BOM (or version catalog)
#   - managed BOMs, which are imported into the BOM that we generate
#   - all other dependencies, which are implementation details
#
# If a library needs to appear in the BOM of the project, then it must be
# declared with the "managed-" prefix.
# If a BOM needs to be imported in the BOM of the project, then it must be
# declared with the "boms-" prefix.
# Both managed dependencies and BOMs need to have their version declared via

# a managed version (a version which alias starts with "managed-"

[versions]
micronaut-platform = "5.0.5"
micronaut = "5.1.7"
micronaut-security = "5.3.1"
micronaut-views = "6.1.0"
micronaut-reactor = "4.1.0"
micronaut-serde = "3.1.0"
micronaut-micrometer = "6.0.1"
micronaut-object-storage = "3.0.0"
micronaut-cache = "6.1.0"
micronaut-sql = "7.1.0"
micronaut-data = "5.1.0"
micronaut-testresources = "4.0.0"
micronaut-gradle-plugin = "5.0.2"
micronaut-openapi = "7.0.0"
micronaut-kafka = "6.0.0"
kotlin-gradle-plugin = "2.4.10"
micronaut-shared-settings = "8.0.1"
playwright = "1.62.0"
shadow-plugin = "9.3.2"
test-logger-plugin = "4.0.0"
gradle-node-plugin = "7.1.0"
avro = "1.12.2"
avro-serde = "8.2.1"

[libraries]
micronaut-openapi = { module = "io.micronaut.openapi:micronaut-openapi-bom", version.ref = "micronaut-openapi" }
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-security = { module = 'io.micronaut.security:micronaut-security', version.ref = 'micronaut-security' }
micronaut-platform = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut-platform"}
micronaut-views = { module = 'io.micronaut.views:micronaut-views-bom', version.ref = 'micronaut-views' }
micronaut-reactor = { module = 'io.micronaut.reactor:micronaut-reactor-bom', version.ref = 'micronaut-reactor' }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-object-storage = { module = "io.micronaut.objectstorage:micronaut-object-storage-bom", version.ref = "micronaut-object-storage" }
micronaut-cache = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }
micronaut-data = { module = "io.micronaut.data:micronaut-data-bom", version.ref = "micronaut-data" }
micronaut-testresources = { module = 'io.micronaut.testresources:micronaut-test-resources-bom', version.ref = "micronaut-testresources" }
micronaut-kafka = { module = "io.micronaut.kafka:micronaut-kafka-bom", version.ref = "micronaut-kafka" }
avro = { module = "org.apache.avro:avro", version.ref = "avro" }
avro-serde = { module = "io.confluent:kafka-streams-avro-serde", version.ref = "avro-serde" }

playwright = { module = "com.microsoft.playwright:playwright", version.ref = "playwright"}

# Plugins
gradle-micronaut = { module = 'io.micronaut.gradle:micronaut-gradle-plugin', version.ref = 'micronaut-gradle-plugin' }
micronaut-shared-settings = { module = "io.micronaut.build.shared.settings:io.micronaut.build.shared.settings.gradle.plugin", version.ref = "micronaut-shared-settings" }
gradle-kotlin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin-gradle-plugin' }
shadow-plugin = { module = "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin", version.ref = "shadow-plugin" }
test-logger-plugin = { module = "com.adarshr.test-logger:com.adarshr.test-logger.gradle.plugin", version.ref = "test-logger-plugin"}
node-gradle-plugin = { module = "com.github.node-gradle:gradle-node-plugin", version.ref = "gradle-node-plugin" }

[bundles]

[plugins]
