micronaut.control-panel.panels.rabbitmq.enabled = true
micronaut.control-panel.panels.rabbitmq.title = RabbitMQ
micronaut.control-panel.panels.rabbitmq.icon = si si-rabbitmq
micronaut.control-panel.panels.rabbitmq.order = 30
