micronaut.control-panel.panels.opensearch.enabled = true
micronaut.control-panel.panels.opensearch.title = OpenSearch
micronaut.control-panel.panels.opensearch.icon = fa-magnifying-glass-chart
micronaut.control-panel.panels.opensearch.order = 25
