micronaut.control-panel.panels.jackson-xml.enabled = true
micronaut.control-panel.panels.jackson-xml.title = Jackson XML
micronaut.control-panel.panels.jackson-xml.icon = fa-code
micronaut.control-panel.panels.jackson-xml.order = 25
