micronaut.control-panel.panels.elasticsearch.enabled = true
micronaut.control-panel.panels.elasticsearch.title = Elasticsearch
micronaut.control-panel.panels.elasticsearch.icon = si si-elasticsearch
micronaut.control-panel.panels.elasticsearch.order = 25
micronaut.control-panel.panels.elasticsearch.max-indices = 50
micronaut.control-panel.panels.elasticsearch.max-aliases-per-index = 10
micronaut.control-panel.panels.elasticsearch.max-mapping-fields = 50
micronaut.control-panel.panels.elasticsearch.probe-timeout = 5s
