micronaut.control-panel.panels.spring-compatibility.enabled = true
micronaut.control-panel.panels.spring-compatibility.title = Spring Compatibility
micronaut.control-panel.panels.spring-compatibility.icon = si si-spring
micronaut.control-panel.panels.spring-compatibility.order = 30
