micronaut.control-panel.panels.kafka.enabled = true
micronaut.control-panel.panels.kafka.title = Kafka
micronaut.control-panel.panels.kafka.icon = si si-apachekafka
micronaut.control-panel.panels.kafka.order = 50

micronaut.control-panel.panels.kafkastreams.enabled = true
micronaut.control-panel.panels.kafkastreams.title = Kafka Streams
micronaut.control-panel.panels.kafkastreams.icon = si si-apachekafka
micronaut.control-panel.panels.kafkastreams.order = 51
