micronaut.control-panel.panels.kafka.enabled = true
micronaut.control-panel.panels.kafka.title = Kafka
micronaut.control-panel.panels.kafka.icon = fa-diagram-project
micronaut.control-panel.panels.kafka.order = 50
