micronaut.control-panel.panels.kafka-cluster.enabled = true
micronaut.control-panel.panels.kafka-cluster.icon = si si-apachekafka
micronaut.control-panel.panels.kafka-cluster.order = 10
micronaut.control-panel.panels.kafka-streams.enabled = true
micronaut.control-panel.panels.kafka-streams.icon = si si-apachekafka
micronaut.control-panel.panels.kafka-streams.order = 20
micronaut.control-panel.kafka.writes.enabled = false
micronaut.control-panel.kafka.writes.destructive-enabled = false
