micronaut.control-panel.panels.graalpy.enabled = true
micronaut.control-panel.panels.graalpy.title = GraalPy
micronaut.control-panel.panels.graalpy.icon = fa-brands fa-python
micronaut.control-panel.panels.graalpy.order = 20
