insert into team(name, stadium) values ('Real Madrid', 'Santiago Bernabéu');
insert into team(name, stadium) values ('FC Barcelona', 'Camp Nou');
insert into team(name, stadium) values ('Manchester United', 'Old Trafford');
insert into team(name, stadium) values ('Chelsea', 'Stamford Bridge');
insert into team(name, stadium) values ('Paris Saint-Germain', 'Parc des Princes');
insert into team(name, stadium) values ('Olympique de Marseille', 'Stade Vélodrome');
insert into team(name, stadium) values ('Bayern Munich', 'Allianz Arena');
insert into team(name, stadium) values ('Borussia Dortmund', 'Signal Iduna Park');
insert into team(name, stadium) values ('Juventus', 'Juventus Stadium');
insert into team(name, stadium) values ('Inter Milan', 'Giuseppe Meazza');