micronaut.control-panel.panels.pulsar.enabled = true
micronaut.control-panel.panels.pulsar.title = Pulsar
micronaut.control-panel.panels.pulsar.icon = si si-apachepulsar
micronaut.control-panel.panels.pulsar.order = 30
