name: Temporary GraalVM Dev Native Verification

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+.x'

jobs:
  graalvm_dev_native_test:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      DEVELOCITY_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      DEVELOCITY_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
    steps:
      - name: Remove system JDKs
        run: |
          sudo rm -rf /usr/lib/jvm/*
          unset JAVA_HOME
          export PATH=$(echo "$PATH" | tr ':' '\n' | grep -v '/usr/lib/jvm' | paste -sd:)

      - uses: actions/checkout@v6

      - name: Pre-Build Steps
        uses: micronaut-projects/github-actions/graalvm/pre-build@master
        with:
          java: dev
          distribution: graalvm-community
          nativeTestTask: micronaut-doc-examples:micronaut-example-java:nativeTest

      - name: Build Steps
        uses: micronaut-projects/github-actions/graalvm/build@master
        env:
          GH_TOKEN_PUBLIC_REPOS_READONLY: ${{ secrets.GH_TOKEN_PUBLIC_REPOS_READONLY }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GRAALVM_QUICK_BUILD: true
        with:
          nativeTestTask: micronaut-doc-examples:micronaut-example-java:nativeTest

      - name: Post-Build Steps
        if: always()
        uses: micronaut-projects/github-actions/graalvm/post-build@master
        with:
          java: dev
